[package]
authors.workspace = true
categories = ["localization", "internationalization"]
description = "Macro implementations for i18n-embed"
edition.workspace = true
keywords = ["build", "i18n", "gettext", "locale", "fluent"]
license.workspace = true
name = "i18n-embed-impl"
readme = "../README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.8.4"

[badges]
maintenance = { status = "actively-developed" }

[lib]
proc-macro = true

[dependencies]
find-crate = { workspace = true, optional = true }
i18n-config = { workspace = true, optional = true }
proc-macro2 = { workspace = true }
quote = { workspace = true, optional = true }
syn.workspace = true

[features]
default = []
fluent-system = ["dep:i18n-config", "dep:find-crate", "dep:quote"]
gettext-system = ["dep:i18n-config", "dep:find-crate", "dep:quote"]
