[package]
authors.workspace = true
categories = ["localization", "internationalization", "development-tools"]
description = "Macro to perform compile time checks when using the i18n-embed crate and the fluent localization system"
edition.workspace = true
license.workspace = true
name = "i18n-embed-fl"
repository.workspace = true
rust-version.workspace = true
version = "0.10.1"

[lib]
proc-macro = true

[dependencies]
dashmap = { version = "6.2", optional = true }
find-crate = { workspace = true }
fluent = { workspace = true }
fluent-syntax = { workspace = true }
i18n-config = { workspace = true }
i18n-embed = { workspace = true, features = [
  "fluent-system",
  "filesystem-assets",
] }
proc-macro-error3 = "3.1"
proc-macro2 = { workspace = true }
quote = { workspace = true }
strsim = "0.11"
syn.workspace = true
unic-langid = { workspace = true }

[dev-dependencies]
doc-comment = { workspace = true }
pretty_assertions = { workspace = true }
rust-embed = { workspace = true }

[features]
# Uses dashmap implementation for `fl!()` macro lookups.
dashmap = ["dep:dashmap"]
