[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "bin"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
env_logger.workspace = true
i18n-embed = { workspace = true, features = [
  "fluent-system",
  "system-requester",
] }
library-fluent = { path = "../library-fluent/" }

[lints]
workspace = true
