[package]
authors.workspace = true
categories = [
  "localization",
  "internationalization",
  "development-tools::build-utils",
  "wasm",
]
description = "Traits and macros to conveniently embed localization assets into your application binary or library in order to localize it at runtime."
edition.workspace = true
exclude = ["i18n/", "i18n.toml"]
keywords = ["embed", "macro", "i18n", "gettext", "fluent"]
license.workspace = true
name = "i18n-embed"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.16.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
arc-swap = { workspace = true, optional = true }
fluent = { workspace = true, optional = true }
fluent-langneg.workspace = true
fluent-syntax = { workspace = true, optional = true }
gettext = { workspace = true, optional = true }
i18n-embed-impl = { workspace = true, optional = true }
intl-memoizer = { workspace = true, optional = true }
log.workspace = true
notify = { workspace = true, optional = true }
parking_lot = { workspace = true, optional = true }
rust-embed = { workspace = true, optional = true }
sys-locale = { workspace = true, optional = true }
thiserror.workspace = true
tr = { workspace = true, optional = true }
unic-langid.workspace = true
walkdir = { workspace = true, optional = true }
web-sys = { version = "0.3", features = [
  "Window",
  "Navigator",
], optional = true }

[dev-dependencies]
env_logger.workspace = true
pretty_assertions.workspace = true
serial_test.workspace = true

[features]
default = ["rust-embed"]

fluent-system = [
  "dep:fluent",
  "dep:fluent-syntax",
  "dep:intl-memoizer",
  "dep:parking_lot",
  "dep:i18n-embed-impl",
  "i18n-embed-impl/fluent-system",
  "dep:arc-swap",
]
gettext-system = [
  "dep:tr",
  "dep:gettext",
  "dep:parking_lot",
  "dep:i18n-embed-impl",
  "i18n-embed-impl/gettext-system",
]

desktop-requester = ["dep:sys-locale"]
web-sys-requester = ["dep:web-sys"]

filesystem-assets = ["dep:walkdir"]

autoreload = ["dep:notify"]

[lints]
workspace = true
