[package]
authors = ["Luke Frisken <l.frisken@gmail.com>"]
edition = "2018"
name = "library-fluent"
version = "0.2.0"

[dependencies]
i18n-embed = { workspace = true, features = ["fluent-system", "autoreload"] }
i18n-embed-fl = { workspace = true }
once_cell = { workspace = true }
rust-embed = { workspace = true }
