[package]
authors.workspace = true
categories = [
  "localization",
  "internationalization",
  "development-tools::build-utils",
]
description = "Designed for use within the cargo-i18n tool for localizing crates. It has been published to allow its direct use within project build scripts if required."
edition.workspace = true
keywords = ["script", "build", "i18n", "gettext", "locale"]
license.workspace = true
name = "i18n-build"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.10.3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
anyhow = { workspace = true }
i18n-config = { workspace = true }
i18n-embed = { workspace = true, features = [
  "gettext-system",
  "desktop-requester",
], optional = true }
log = { workspace = true }
rust-embed = { workspace = true, optional = true }
thiserror = { workspace = true }
tr.workspace = true
walkdir = { workspace = true }

[features]
default = []

# A feature to localize this library
localize = ["dep:i18n-embed", "dep:rust-embed"]

[lints]
workspace = true
