[package]
authors.workspace = true
categories = ["localization", "internationalization"]
description = "This library contains the configuration stucts (along with their parsing functions) for the cargo-i18n tool/system."
edition.workspace = true
keywords = ["cargo", "build", "i18n", "gettext", "locale"]
license.workspace = true
name = "i18n-config"
readme = "README.md"
repository.workspace = true
rust-version.workspace = true
version = "0.4.8"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
basic-toml = "0.1"
log.workspace = true
serde.workspace = true
thiserror.workspace = true
unic-langid.workspace = true

[lints]
workspace = true
