name: Rust

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run --workspace --all-features

  tidy:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: taiki-e/install-action@taplo-cli
      - uses: taiki-e/install-action@cargo-shear
      - parallel:
        - name: Run rustfmt
          run: cargo fmt --all --check
        - name: Run taplo (lint)
          run: taplo lint
        - name: Run taplo (format)
          run: taplo fmt --check
        - name: Check for unused dependencies
          run: cargo shear --deny-warnings
        - name: Spell Check Repo
          uses: crate-ci/typos@v1

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-all-features
      - parallel:
          - name: Run Clippy (i18n-build)
            working-directory: i18n-build
            run: cargo all-features clippy --all-targets -- -Dwarnings
          - name: Run Clippy (i18n-embed)
            working-directory: i18n-embed
            run: cargo all-features clippy --all-targets -- -Dwarnings
          - name: Run Clippy (i18n-embed-impl)
            working-directory: i18n-embed/i18n-embed-impl
            run: cargo all-features clippy --all-targets -- -Dwarnings
          - name: Run Clippy (i18n-embed-fl)
            working-directory: i18n-embed-fl
            run: cargo all-features clippy --all-targets -- -Dwarnings
          - name: Run Clippy (examples)
            run: cargo all-features clippy --examples -- -Dwarnings
  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-msrv
      - name: Run cargo-msrv
        run: cargo msrv verify
