name: Rust

on:
  pull_request:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@nextest
      - name: Run tests
        run: cargo nextest run --workspace --all-features

  tidy:
    name: Static Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: taiki-e/install-action@taplo-cli
      - uses: actions/setup-node@v7
      - parallel:
          - name: Run rustfmt
            run: cargo fmt --all --check
          - name: Run taplo (lint)
            run: taplo lint
          - name: Run taplo (format)
            run: taplo fmt --check
          - name: Spell Check Repo
            uses: crate-ci/typos@v1
          - name: Formatting (Markdown/JSON/YAML)
            run: npx prettier --check .

  clippy-stable:
    name: Clippy (Stable)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-all-features
      - name: Run Clippy
        run: cargo all-features clippy --all-targets -- -Dwarnings

  clippy-nightly:
    name: Clippy (Nightly)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-all-features
      - name: Run Clippy
        run: |
          # Because cargo lints are only stable as of 1.100, putting this in Cargo.toml causes warnings for anyone before that version
          printf '[workspace.lints.cargo]\ndefault="deny"' >> Cargo.toml
          cargo all-features clippy --all-targets -- -Dwarnings

  msrv:
    name: Check MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-msrv
      - name: Run cargo-msrv
        run: cargo msrv verify
  doc:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@stable
      - name: Document workspace
        env:
          RUSTDOCFLAG: -Dwarnings --cfg docsrs
        run: cargo doc --workspace --all-features --no-deps
